services:
  mongodb:
    image: mongo:5.0.2
    container_name: mongodb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - belcorp_db:/data/db
      - ./scripts/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - backend

  belcorp-backend:
    depends_on:
      - mongodb
    build: ./belcorp-backend
    container_name: belcorp_backend
    restart: unless-stopped
    volumes:
      - ./belcorp-backend/src:/usr/src/belcorp-backend/src
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - backend
      - frontend

  belcorp-frontend:
    depends_on:
      - belcorp-backend
    build:
      context: ./belcorp-frontend
    container_name: belcorp_frontend
    restart: unless-stopped
    volumes:
      - ./belcorp-frontend/src:/usr/src/belcorp-frontend/src
    env_file: ./.env
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend

volumes: 
  belcorp_db:

networks:
  backend:
  frontend:
